
# Site settings
title: Readrz Blog
email: andrey@readrz.com

description: >
  This is the Readrz.com development blog.
  Feel free to get in touch is you want to discuss anything.

url: "http://blog.readrz.com"
baseurl: "/readrz-blog"

twitter_username: akuz_me
github_username:  akuz

# Permalinks
permalink: pretty

# Build settings
markdown: kramdown
#markdown: redcarpet

# Pagination
paginate: 5

url_readrz: "http://www.readrz.com"
url_subscribe: "http://eepurl.com/d48hj"

picture:
  source: _imgfullsize
  output: generated
  markup: picture
  presets:
    # Full width pictures
    default:
      ppi: [1, 1.5]
      attr:
        class: blog-full
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200