
# Site settings
title: Readrz Blog
email: andrey@readrz.com

description: >
  This is the Readrz.com development blog.
  Feel free to get in touch is you want to discuss anything.

url: "http://blog.readrz.com"
baseurl: "/readrz-blog"

twitter_username: akuz_me
github_username:  akuz

# Permalinks
permalink: pretty

# Build settings
markdown: kramdown
#markdown: redcarpet

# Pagination
paginate: 5

url_readrz: "http://www.readrz.com"
url_subscribe: "http://eepurl.com/d48hj"